### ISSUE TITLE
Not changing tags with a namespace

### ISSUE THREAD

**Issue by guygriffiths** [dsandstrom/atom-double-tag#42] opened 2018-06-28 10:44 UTC
If I am editing XML which uses different namespaces, the tags with namespaces do not get changed, when this package is enabled.

Example XML which demonstrates the issue:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<StartTag xmlns="http://defaultnamespace.com" xmlns:other="http://othernamespace.com">
    <Tag1>
        This tag will get changed with atom-double-tag
    </Tag1>
    <other:Tag2>
        This tag will not get changed
    </other:Tag2>
</StartTag>
```

**Comment by dsandstrom** [comment] 2018-09-07 19:58
Duplicate of #19

**Closed by dsandstrom** 2018-09-07 19:58 UTC
Labels: enhancement
