### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /<\/?t('actions.edit_model',[>\s]/: Unterminate...

### ISSUE THREAD

**Issue by caiofct** [dsandstrom/atom-double-tag#8] opened 2016-07-29 13:30 UTC
Steps to reproduce:

1. Typed a ruby tag on erb <%=%>
2. The package gives the error below

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [double-tag](https://github.com/dsandstrom/atom-double-tag) package, v0.2.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /<\/?t('actions.edit_model',[>\s]/: Unterminated group

```
At /Users/caiofct/.atom/packages/double-tag/lib/double-tag.coffee:105

SyntaxError: Invalid regular expression: /<\/?t('actions.edit_model',[>\s]/: Unterminated group
    at new RegExp (native)
    at DoubleTag.module.exports.DoubleTag.findEndTag (/Users/caiofct/.atom/packages/double-tag/lib/double-tag.coffee:105:20)
    at DoubleTag.module.exports.DoubleTag.findTag (/Users/caiofct/.atom/packages/double-tag/lib/double-tag.coffee:42:20)
    at /Users/caiofct/.atom/packages/double-tag/lib/double-tag.coffee:22:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1786:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:927:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:288:27
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:284:46)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1344:34)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:852:12)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1328:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2224:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:832:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:504:26)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -0:38.3.0 find-and-replace:show (atom-text-editor.editor.mini.is-focused)
     -0:38.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:37.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:33.9.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:30.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:25.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:25 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:18.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:04.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "atom-beautify",
      "rubocop-auto-correct"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
double-tag, v0.2.0
highlight-selected, v0.11.2
language-javascript-jsx, v0.3.7
open-recent, v5.0.0
package-sync, v1.1.0
pigments, v0.31.2
rails-i18n-autocomplete, v0.4.0
react, v0.15.0
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by dsandstrom** [comment] 2016-07-29 19:23
Thanks.  I couldn't reproduce this.  Can you provide a reduced example of the file where the error occurs?  I think it has something to do with content on that page.

**Comment by caiofct** [comment] 2016-07-29 19:42
The file was an .html.erb
I was trying to insert a translation for a string using the Rails t method: <%=t('')%>
Sometimes that I inserted this code, the exception came out.
From the stack trace it seems something todo with your regular expression. Maybe the quotation marks are involved?

**Comment by dsandstrom** [comment] 2016-07-29 20:06
Does it happen if you use spaces inside your ERB tag: `<%= t %>?

**Comment by dsandstrom** [comment] 2016-07-29 20:55
Sorry, still can't reproduce.  Please provide a file that you can always make the problem occur on.

**Comment by dsandstrom** [comment] 2016-08-10 17:31
I was able to reproduce with something like `<foo <%=foo(first, last)%>></foo>`.  This should be fixed in master.  Let me know if you still are seeing a problem after the next release.

**Closed by dsandstrom** 2016-08-10 17:31 UTC
Labels: more information needed
